### ISSUE TITLE
Crash on OpenBSD

### ISSUE THREAD

**Issue by vext01** [gabrielmagno/nano-dlna#16]
```
$ ~/.local/bin/nanodlna list
nano-dlna log will be saved here: /tmp/tmp02_tdvqe/nanodlna-2021-10-08_11-36-16.log
Traceback (most recent call last):
  File "/home/edd/.local/bin/nanodlna", line 8, in <module>
    sys.exit(run())
  File "/home/edd/.local/lib/python3.8/site-packages/nanodlna/cli.py", line 150, in run
    args.func(args)
  File "/home/edd/.local/lib/python3.8/site-packages/nanodlna/cli.py", line 55, in list_devices
    my_devices = devices.get_devices(args.timeout)
  File "/home/edd/.local/lib/python3.8/site-packages/nanodlna/devices.py", line 77, in get_devices
    s.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 4)
OSError: [Errno 22] Invalid argument
```

Any ideas?

**Comment by gabrielmagno** [comment]
Forgot to mention, but `gssdp-discover` is part of the `gupnp-tools` project (https://github.com/GNOME/gupnp-tools), so since you already have `gupnp-av-cp`, I believe you will already have `gssdp-discover` available.

**Comment by gabrielmagno** [comment]
Hi @vext01.

Sorry for the late follow up on this.

I have added a new fix into the bugfix/openbsd. Basically, I bind to `0.0.0.0` by default now (instead of empty string), and also, if a host is provided, use that as the IP to bind.

First try normally as before:
```
nanodlna -b list
```

If it does not work, try this (replacing `10.x.x.x` by the local network address of the interface `em0`)
```
nanodlna -b -H 10.x.x.x list
```

Could you git pull the branch, reinstall nano-dlna, and check if it works now?

Thank you.
