### ISSUE TITLE
traceback when devices does not support expected UPNP_DEFAULT_SERVICE_TYPE

### ISSUE THREAD

**Issue by jamincollins** [gabrielmagno/nano-dlna#5]
While attempting to test version 0.1.6, I encountered the following traceback:
```
$ nanodlna list
Traceback (most recent call last):
  File "/bin/nanodlna", line 11, in <module>
    load_entry_point('nanodlna==0.1.6', 'console_scripts', 'nanodlna')()
  File "/usr/lib/python3.6/site-packages/nanodlna/cli.py", line 96, in run
    args.func(args)
  File "/usr/lib/python3.6/site-packages/nanodlna/cli.py", line 26, in list_devices
    my_devices = devices.get_devices(args.timeout)
  File "/usr/lib/python3.6/site-packages/nanodlna/devices.py", line 87, in get_devices
    devices = [register_device(location_url) for location_url in devices_urls]
  File "/usr/lib/python3.6/site-packages/nanodlna/devices.py", line 87, in <listcomp>
    devices = [register_device(location_url) for location_url in devices_urls]
  File "/usr/lib/python3.6/site-packages/nanodlna/devices.py", line 42, in register_device
    UPNP_DEFAULT_SERVICE_TYPE
AttributeError: 'NoneType' object has no attribute 'text'
````
Digging into this a bit it appears nanodlna is expecting DLNA devices to advertise one specific service type: **urn:schemas-upnp-org:service:AVTransport:1**

However, the device in question here (Sonos CONNECT:AMP) does not advertise this service.

After applying the following patch, I found that a second DLNA device on the network also does not advertise this service, [Rygel](https://wiki.gnome.org/action/show/Projects/Rygel?action=show&redirect=Rygel) under Linux.

```
$ git diff
diff --git a/nanodlna/devices.py b/nanodlna/devices.py
index 2e95e96..106bc64 100644
--- a/nanodlna/devices.py
+++ b/nanodlna/devices.py
@@ -37,12 +37,15 @@ def register_device(location_url):
 
     friendly_name = info.find("./device/friendlyName").text
 
-    path = info.find(
-        "./device/serviceList/service/[serviceType='{0}']/controlURL".format(
-            UPNP_DEFAULT_SERVICE_TYPE
-        )
-    ).text
-    action_url = urllibparse.urljoin(location_url, path)
+    try:
+        path = info.find(
+            "./device/serviceList/service/[serviceType='{0}']/controlURL".format(
+                UPNP_DEFAULT_SERVICE_TYPE
+            )
+        ).text
+        action_url = urllibparse.urljoin(location_url, path)
+    except AttributeError:
+        action_url = None
 
     device = {
         "location": location_url,
```
I'll fork the project and submit a pull request with the above fix.

**Comment by gabrielmagno** [comment]
Fixed by #6
